/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:650544ae-f77e-4f15-bab7-f78c64138afd",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_s3bXZwGrH",
  aws_user_pools_web_client_id: "6dr5io84vl3m3a6o3hdc4oft5g",
  oauth: {}
};

export default awsmobile;

console.log(awsmobile);
